ENV_ID: "Pulse-Blackjack-Standard"
RESULTS_DIR: "blackjack"

CAPACITY: 1000000
MIN_SAMPLES: 5000
BATCH_SIZE: 1000
NUM_EPISODES: 7500

STATE_DIM: 3
ACTION_DIM: 2

Q_LEARNING_RATE: .99
LEARNING_RATE: 1e-4
WEIGHT_DECAY: 1e-5
EPSILON: 1
UPDATE: 1000
EPSILON_DECAY: .9995
EPSILON_MIN: .01

MU: 0.0
THETA: .15
SIGMA: .2
