ENV_ID: "Pulse-Blackjack-Standard"
RESULTS_DIR: 'blackjack'
BATCH_SIZE: 10000
NUM_EPISODES: 7500

STATE_DIM: 3
ACTION_DIM: 2

Q_LEARNING_RATE: .99
LEARNING_RATE: 1e-4
WEIGHT_DECAY: 1e-5
EPSILON: 1
UPDATE: 1000
EPSILON_DECAY: .9995
EPSILON_MIN: .01