RESULTS_DIR: "PokerGPU"
ENV_ID: "Pulse-Poker-GPU-v1"
PLOT_FILENAME: ""
SCORES_FILENAME: ""
AGENTS:
  - "tight_aggressive"
  - "heuristic_hands"
  - "heuristic_hands"
  - "loose_passive"
  - "tight_aggressive"
  - "random"
  - "loose_passive"
  - "small_ball"
  - "tight_aggressive"

CAPACITY: 100000
N_GAMES: 2500000
EPISODES: 3000

STARTING_BBS: 100
NUM_PLAYERS: 9

STATE_SPACE: 40
ACTION_SPACE: 13

W1: 2
W2: .5
W1_DECAY: .99999
W2_DECAY: .9999
K: 1000
UPDATE_FREQ: 25
GAMMA: .999
ALPHA: 300

