# initialize globals
RESULTS_DIR: "Poker"
ENV_ID: "Pulse-Poker-v1"
PLOT_FILENAME: ""
SCORES_FILENAME: ""
AGENTS:
  - "qlearning"
  - "heuristic"
  - "heuristic"
  - "heuristic"
  - "random"
  - "random"

NUM_ENVS: 4
EPISODES: 10

# poker specific config
SMALL_BLIND: 25
BIG_BLIND: 50
STARTING_STACK: 100
NUM_PLAYERS: 6

# reward function config
W1: 2
W2: .5
W1_DECAY: .99999
W2_DECAY: .9999
K: 100
